// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/logspammer/logspammer.proto

package go_micro_service_logspammer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/ebelanja/go-micro/api"
	client "github.com/ebelanja/go-micro/client"
	server "github.com/ebelanja/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Logspammer service

func NewLogspammerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Logspammer service

type LogspammerService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Logspammer_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Logspammer_PingPongService, error)
}

type logspammerService struct {
	c    client.Client
	name string
}

func NewLogspammerService(name string, c client.Client) LogspammerService {
	return &logspammerService{
		c:    c,
		name: name,
	}
}

func (c *logspammerService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Logspammer.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logspammerService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Logspammer_StreamService, error) {
	req := c.c.NewRequest(c.name, "Logspammer.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &logspammerServiceStream{stream}, nil
}

type Logspammer_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type logspammerServiceStream struct {
	stream client.Stream
}

func (x *logspammerServiceStream) Close() error {
	return x.stream.Close()
}

func (x *logspammerServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *logspammerServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logspammerServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logspammerServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logspammerService) PingPong(ctx context.Context, opts ...client.CallOption) (Logspammer_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Logspammer.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &logspammerServicePingPong{stream}, nil
}

type Logspammer_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type logspammerServicePingPong struct {
	stream client.Stream
}

func (x *logspammerServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *logspammerServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *logspammerServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logspammerServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logspammerServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *logspammerServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Logspammer service

type LogspammerHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Logspammer_StreamStream) error
	PingPong(context.Context, Logspammer_PingPongStream) error
}

func RegisterLogspammerHandler(s server.Server, hdlr LogspammerHandler, opts ...server.HandlerOption) error {
	type logspammer interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Logspammer struct {
		logspammer
	}
	h := &logspammerHandler{hdlr}
	return s.Handle(s.NewHandler(&Logspammer{h}, opts...))
}

type logspammerHandler struct {
	LogspammerHandler
}

func (h *logspammerHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.LogspammerHandler.Call(ctx, in, out)
}

func (h *logspammerHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.LogspammerHandler.Stream(ctx, m, &logspammerStreamStream{stream})
}

type Logspammer_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type logspammerStreamStream struct {
	stream server.Stream
}

func (x *logspammerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *logspammerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *logspammerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logspammerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logspammerStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *logspammerHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.LogspammerHandler.PingPong(ctx, &logspammerPingPongStream{stream})
}

type Logspammer_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type logspammerPingPongStream struct {
	stream server.Stream
}

func (x *logspammerPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *logspammerPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *logspammerPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logspammerPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logspammerPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *logspammerPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
